# Dados de Casos e Óbitos

Os dados de casos e óbitos são filtrados a partir dos dados disponibilizados pelo site (brasil.io)[https://brasil.io]. Os dados mais atualizados são apenas do estado como um todos. Os dados dos municípios não estão atualizados. 

O arquivo de `input` não está incluso nesse repositório por conta do tamanho.

In [2]:
import pandas as pd

In [4]:
dados_vacinacao = pd.read_csv("../input/brasilio/caso_full.csv")

In [16]:
dados_sergipe = dados_vacinacao.query("state == 'SE' and place_type == 'state'").sort_values(by='date')
dados_sergipe = dados_sergipe[['date','epidemiological_week','last_available_confirmed','last_available_deaths','new_confirmed','new_deaths']]
dados_sergipe = dados_sergipe.reset_index(drop=True)
dados_sergipe['mean7_confirmed'] = dados_sergipe['new_confirmed'].rolling(window=7).mean()
dados_sergipe['mean7_deaths'] = dados_sergipe['new_deaths'].rolling(window=7).mean()
dados_sergipe

,date,epidemiological_week,last_available_confirmed,last_available_deaths,new_confirmed,new_deaths,mean7_confirmed,mean7_deaths
0,2020-03-14,202011,1,0,1,0,NaN,NaN
1,2020-03-15,202012,1,0,0,0,NaN,NaN
2,2020-03-16,202012,5,0,4,0,NaN,NaN
3,2020-03-17,202012,5,0,0,0,NaN,NaN
4,2020-03-18,202012,6,0,1,0,NaN,NaN
...,...,...,...,...,...,...,...,...
680,2022-01-23,202204,283671,6074,699,2,494.285714,1.142857
681,2022-01-24,202204,284333,6075,662,1,575.000000,1.142857
682,2022-01-25,202204,284928,6077,595,2,620.000000,1.428571
683,2022-01-26,202204,286187,6079,1259,2,733.428571,1.571429
684,2022-01-27,202204,287212,6081,1025,2,826.000000,1.714286

In [21]:
dados_sergipe.to_csv("../output/se_covid19_casos_obitos.csv", index=False)